#!/bin/bash

# current directory path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
cd $DIR

BASE_DIR="$DIR""/../../../MySQL"
BUILD_DIR="$BASE_DIR""/build"

SOURCE_DIR="$BASE_DIR""/mysql-server"
INST_DIR="$BASE_DIR""/inst"
DATA_DIR="$BASE_DIR""/data"
BOOST_DIR="$BASE_DIR""/boost"

cd $BASE_DIR

rm -rf $BUILD_DIR
mkdir -p $BUILD_DIR
cd $BUILD_DIR


rm -f CMakeCache.txt

COMPILE_OPTION=${1}

cmake $SOURCE_DIR \
	-DCMAKE_INSTALL_PREFIX=$INST_DIR \
	-DMYSQL_UNIX_ADDR=$INST_DIR/mysql.sock \
	-DSYSCONFDIR=$INST_DIR \
	-DMYSQL_DATADIR=$DATA_DIR \
	-DINSTALL_DOCDIR=$INST_DIR \
	-DINSTALL_INFODIR=$INST_DIR \
	-DINSTALL_DOCREADMEDIR=$INST_DIR \
	-DCMAKE_BUILD_TYPE=Release \
	-DMYSQL_TCP_PORT=5555 \
	-DENABLED_LOCAL_INFILE=1 \
	-DWITH_BOOST=$BOOST_DIR \
	-DWITH_JEMALLOC=1 \
	-DCMAKE_CXX_FLAGS="${COMPILE_OPTION}" \
	-DCMAKE_C_FLAGS="${COMPILE_OPTION}" \
  -DWITH_MYSQLX=0 \
#	-DDOWNLOAD_BOOST=1 \
#	-DCMAKE_C_COMPILER="/usr/bin/gcc-10" \
#	-DCMAKE_CXX_COMPILER="/usr/bin/g++-10" \
#	-D_FILE_OFFSET_BITS=64 \
#	-DWITH_DEBUG=0 \
#	-DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O0 -g -DNDEBUG" \

cd $DIR
